import wizard
import res_partner
import sale
import account_invoice
import product
import reasons
import returns
import crm_helpdesk
import stock
import email_template
import report
import credit_service
import vista_delivery
import sale_import
import mrp
import service_config
#import sale_bundle_product
#import test_svn

